spring:
  profiles:
    active: local
  application:
    name: javadoc-server
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/db_jdoc
    username: root
    password: 123456
    driver-class-name: org.postgresql.Driver
    platform: postgres
  # 使用高性能的 caffeine 做缓存.
  cache:
    type: caffeine
    cache-names: javadoc
    caffeine:
      spec: maximumSize=2000,expireAfterAccess=600s
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: false # 启动时是否初始化数据库
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false # 必须加这个，否则PG会报错.

# 服务端口，将默认为1010.
server:
  port: 1010

# 日志相关的简单配置.
logging:
  file: logs/javadoc-server.log
  level:
    root: info
    org:
      apache: warn
      springframework: warn

# 本系统服务相关的配置项.
system:
  # 本服务基础的 baseUrl 地址
  baseUrl: http://127.0.0.1:1010
  # MinIO 的别名和用来存 javadoc 的桶.
  minio:
    endpoint: http://127.0.0.1:9000
    accessKey: minio
    secretKey: 12345678
    alias: javadoc
    bucket: docs
  # 去下载 javadoc 资源的 maven 仓库地址.
  mvnRepos:
    - https://repo1.maven.org/maven2
    - http://repo.spring.io/libs-milestone
    - http://jcenter.bintray.com